"""
SQLAlchemy model for the `admin_access_codes` table.

A code is generated by an existing super_admin and shown ONCE in plaintext
to the inviter. The hash is stored. Purpose distinguishes invite vs reset.
"""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import Optional

from sqlalchemy import DateTime, ForeignKey, String
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy.orm import Mapped, mapped_column

from .base import Base, TimestampMixin, UUIDPrimaryKeyMixin


class AdminAccessCode(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    __tablename__ = "admin_access_codes"

    email: Mapped[str] = mapped_column(String(320), nullable=False)
    code_hash: Mapped[str] = mapped_column(String(255), nullable=False)
    purpose: Mapped[str] = mapped_column(String(20), nullable=False)
    superuser_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("superusers.id", ondelete="CASCADE"),
        nullable=True,
    )
    invited_role: Mapped[Optional[str]] = mapped_column(String(30), nullable=True)
    invited_first_name: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)
    invited_last_name: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)
    used_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    expires_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False
    )
    created_by: Mapped[uuid.UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("superusers.id", ondelete="RESTRICT"),
        nullable=False,
    )
