-- Migration 014: admin_access_codes table for superuser invite + password reset codes.
-- Codes are generated by an existing super_admin from the admin dashboard,
-- shown once in plaintext, and stored as bcrypt hash.
--
-- Purpose values:
--   'invite' -- first-time onboarding; superuser_id is NULL until redeemed.
--   'reset'  -- password reset for an existing superuser; superuser_id required.

CREATE TABLE IF NOT EXISTS admin_access_codes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email VARCHAR(320) NOT NULL,
    code_hash VARCHAR(255) NOT NULL,
    purpose VARCHAR(20) NOT NULL CHECK (purpose IN ('invite', 'reset')),
    superuser_id UUID NULL REFERENCES superusers(id) ON DELETE CASCADE,
    invited_role VARCHAR(30) NULL,
    invited_first_name VARCHAR(100) NULL,
    invited_last_name VARCHAR(100) NULL,
    used_at TIMESTAMPTZ NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    created_by UUID NOT NULL REFERENCES superusers(id) ON DELETE RESTRICT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_admin_codes_email_purpose
    ON admin_access_codes(email, purpose) WHERE used_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_admin_codes_superuser
    ON admin_access_codes(superuser_id) WHERE superuser_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_admin_codes_expires
    ON admin_access_codes(expires_at) WHERE used_at IS NULL;
