/**
 * VISP legal copy for the public web (Terms + Privacy).
 * Kept in sync with the mobile app screens
 * (vispapp/src/screens/profile/TermsScreen.tsx + PrivacyPolicyScreen.tsx).
 * English only — the public landing is English.
 */

export interface LegalSection {
  heading: string;
  body: string;
}

export interface LegalDoc {
  title: string;
  subtitle: string;
  sections: LegalSection[];
}

export const TERMS: LegalDoc = {
  title: 'VISP — Terms and Conditions',
  subtitle:
    'Verified Independent Service Provider Platform | Effective Date: May 01, 2026 | Version 1.0',
  sections: [
    { heading: '1. Introduction', body: 'Welcome to VISP ("VISP", "we", "us", or "our"). VISP operates a digital marketplace platform (the "Platform") that connects individuals and businesses seeking services ("Clients") with independent service providers ("Service Providers"). VISP is a marketplace and technology service. We are not the employer, agent, contractor, or representative of any Service Provider, and we do not perform any services listed on the Platform.\n\nThese Terms and Conditions ("Terms") govern your access to and use of the VISP mobile application, website, and related services. By creating an account or using the Platform, you acknowledge that you have read, understood, and agree to be bound by these Terms. If you do not agree, do not use the Platform.' },
    { heading: '2. Eligibility', body: '• You must be at least 18 years of age and capable of forming a legally binding contract.\n• You must reside in Canada and be legally permitted to use marketplace services in your province or territory.\n• Service Providers must be legally entitled to perform the services they offer, including holding all required licenses, permits, and certifications where applicable.\n• You agree to provide accurate, current, and complete information during registration and to keep that information up to date.' },
    { heading: '3. Service Provider Tiers and Verification', body: 'VISP uses a tiered verification system to help Clients understand the level of trust and qualification associated with each Service Provider. Tier assignment is determined by VISP at its sole discretion based on the information and documentation provided.\n\nTier 1 — New / Unverified: Newly registered accounts that have not yet completed full verification. Limited access to job categories.\n\nTier 2 — Verified General Services: Service Providers who have completed identity verification and background screening. May offer general, non-regulated services.\n\nTier 3 — Licensed / Regulated Services: Service Providers who have submitted and had verified all licenses, certifications, and permits required to legally perform regulated services.\n\nTier 4 — Restricted (Not Permitted): Covers emergency, high-risk, and otherwise prohibited activities. VISP does not facilitate Tier 4 services.' },
    { heading: '4. Prohibited Services and Conduct', body: 'The following are strictly prohibited on the Platform:\n\n• Any illegal activity or service that violates Canadian federal, provincial, or municipal law.\n• Emergency services, medical treatment, or life-safety services (please contact 911).\n• Sexual services, escort services, or any form of adult-for-hire activity.\n• Services requiring a license or certification that the Service Provider does not hold.\n• Harassment, threats, hate speech, discrimination, or any abusive conduct toward other users or VISP staff.\n• Soliciting Clients or Service Providers to transact outside of the Platform to circumvent fees or oversight.\n• Misrepresenting your identity, qualifications, license status, or insurance coverage.\n• Creating multiple accounts, manipulating ratings, or using bots or automated tools.\n\nVISP reserves the right to suspend or terminate any account, remove listings, or refuse service at our sole discretion if we believe these Terms have been violated.' },
    { heading: "5. VISP's Role as a Marketplace", body: 'VISP is a marketplace, not a service provider. VISP does not employ, supervise, or direct Service Providers. Service Providers are independent contractors who set their own availability, methods, and pricing within the limits permitted by the Platform. The contract for any service is formed directly between the Client and the Service Provider.\n\nWhile VISP performs identity verification, background screening, and license checks where applicable, verification is a process of reasonable diligence and is not a guarantee of skill, character, performance, safety, or outcome. Clients are responsible for evaluating Service Providers and the suitability of any service before booking.' },
    { heading: '6. Bookings, Payments, and Fees', body: '• All payments must be processed through the Platform using our payment processor, Stripe. Off-platform payments are prohibited and not protected by these Terms.\n• VISP charges a service fee (commission) on each transaction. The fee structure is disclosed in the Platform and may be updated from time to time with reasonable notice.\n• Service Providers receive payouts via Stripe, subject to Stripe\'s terms, processing times, and verification requirements.\n• Applicable taxes (including GST/HST/PST/QST) are the responsibility of the party legally required to collect and remit them.\n• Refunds, cancellations, and chargebacks are governed by VISP\'s Refund and Cancellation Policy, which forms part of these Terms.' },
    { heading: '7. Reviews, Ratings, and Dispute Resolution', body: 'Clients and Service Providers may rate and review each other after a job is completed. Reviews must be honest, lawful, and free of personal attacks, discriminatory language, or confidential information.\n\nIf a dispute arises regarding a completed or attempted service, both parties are expected to participate in VISP\'s dispute resolution process, which may include:\n\n• Submitting before-and-after photos of the worksite.\n• Engaging in a moderated chat between the Client, the Service Provider, and a VISP representative.\n• Providing receipts, communications, or other relevant evidence requested by VISP.\n\nVISP will review the evidence in good faith and may issue refunds, withhold payouts, or take account-level action. VISP\'s decisions in dispute resolution are final at the platform level but do not waive any legal rights either party may have outside the Platform.' },
    { heading: '8. Limitation of Liability', body: 'To the fullest extent permitted by applicable law, VISP, its affiliates, officers, directors, employees, and agents are not liable for:\n\n• The acts, omissions, conduct, quality of work, or injuries caused by any Service Provider or Client.\n• Damage to property, personal injury, financial loss, or any consequential damages arising from a service booked through the Platform.\n• Disputes between Clients and Service Providers regarding the scope, quality, or timing of services.\n• Misrepresentations made by users in their profiles, listings, or communications.\n• Any loss caused by Platform downtime, technical errors, or third-party service failures (including Stripe).\n\nVerification badges, tier indicators, and reviews are informational only. They are not guarantees of safety, competence, or outcome. Clients use the Platform at their own risk.' },
    { heading: '9. Indemnification', body: 'You agree to indemnify, defend, and hold harmless VISP and its affiliates from any claims, damages, liabilities, losses, costs, or expenses (including reasonable legal fees) arising out of or related to: (a) your use of the Platform; (b) your violation of these Terms; (c) your violation of any law or third-party right; or (d) any service you offer, perform, or receive through the Platform.' },
    { heading: '10. Suspension and Termination', body: 'VISP may suspend or terminate your account at any time, with or without notice, if we reasonably believe you have violated these Terms, posed a safety risk, or engaged in fraud. You may close your account at any time through the Platform. Upon account deletion, your data will be handled in accordance with our Privacy Policy.' },
    { heading: '11. Intellectual Property', body: 'All Platform content, including logos, designs, software, and trademarks, is owned by VISP or its licensors. You receive a limited, non-exclusive, non-transferable license to use the Platform solely as intended. You retain ownership of content you submit (such as photos and reviews) but grant VISP a worldwide, royalty-free license to use, host, display, and distribute that content in connection with operating the Platform.' },
    { heading: '12. Governing Law and Jurisdiction', body: 'These Terms are governed by the laws of the Province of Ontario and the federal laws of Canada applicable therein, without regard to conflict-of-laws principles. The parties submit to the exclusive jurisdiction of the courts located in Ontario for any dispute that cannot be resolved through VISP\'s internal dispute resolution process, subject to any non-waivable consumer-protection rights you may have in your home province.' },
    { heading: '13. Changes to These Terms', body: 'We may update these Terms from time to time. Material changes will be communicated through the Platform or by email at least 14 days before they take effect, where reasonably practicable. Continued use of the Platform after the effective date constitutes acceptance of the updated Terms.' },
    { heading: '14. Contact Us', body: 'Questions about these Terms can be sent to support@vispapp.com (or such other address as VISP may publish on the Platform).' },
  ],
};

export const PRIVACY: LegalDoc = {
  title: 'VISP — Privacy Policy',
  subtitle:
    'Verified Independent Service Provider Platform | Effective Date: May 01, 2026 | Version 1.0',
  sections: [
    { heading: '1. Introduction', body: 'VISP ("VISP", "we", "us", or "our") respects your privacy and is committed to protecting your personal information. This Privacy Policy explains what information we collect, how we use and share it, how long we keep it, and the choices you have. It applies to your use of the VISP mobile application, website, and related services (the "Platform").\n\nVISP currently operates only in Canada. We comply with the Personal Information Protection and Electronic Documents Act (PIPEDA) and applicable provincial privacy legislation.' },
    { heading: '2. Information We Collect', body: '2.1 Information from All Users\n\n• Account information: name, email address, phone number, password, and profile photo.\n• Location information: approximate or precise location (with your permission) used to match Clients with nearby Service Providers.\n• Communications: messages, dispute submissions, photos, reviews, and ratings exchanged on the Platform.\n• Device and usage data: device identifiers, IP address, operating system, app version, in-app actions, and crash logs.\n• Payment information: payment is processed by Stripe. VISP does not store full payment card numbers; we receive limited transaction data (such as last four digits, transaction ID, and status) from Stripe.\n\n2.2 Additional Information from Service Providers\n\n• Identity verification documents: government-issued ID, selfie/liveness checks, and supporting documents required to confirm identity.\n• Background check information: information collected for criminal-record screening and related risk checks.\n• Professional credentials: licenses, certifications, insurance certificates, and other documents required for Tier 3 services.\n• Banking/payout information: handled directly by Stripe in accordance with Stripe\'s privacy notices.' },
    { heading: '3. How We Collect Information', body: '• Directly from you when you register, complete a profile, book a service, message a user, or submit a dispute.\n• Automatically from your device when you use the Platform (cookies, SDKs, analytics).\n• From third-party services such as Stripe (payments) and any background-check or fraud-prevention partners we engage in the future.' },
    { heading: '4. How We Use Your Information', body: 'We use personal information to:\n\n• Create and maintain your account and profile.\n• Match Clients with Service Providers and facilitate bookings.\n• Verify identity, run background checks, and confirm professional licenses for Tier 3 access.\n• Process payments and payouts through Stripe and calculate platform fees.\n• Operate reviews, ratings, dispute resolution, and trust-and-safety functions.\n• Communicate with you about your account, transactions, support requests, and policy updates.\n• Detect, prevent, and address fraud, abuse, security incidents, and violations of our Terms.\n• Comply with legal obligations and respond to lawful requests from regulators or law enforcement.\n• Improve, secure, and develop new features for the Platform.' },
    { heading: '5. How We Share Information', body: 'We share personal information only as described below:\n\n• Between Clients and Service Providers: limited profile information (name, photo, ratings, location range, tier badge, and messages) is shared to facilitate bookings.\n• Service providers acting on our behalf: Stripe (payments), cloud hosting and analytics providers, customer-support tools, and (where applicable) background-check partners. These providers are bound by confidentiality and data-protection obligations.\n• Legal and safety: we may disclose information when required by law, court order, or to protect the rights, property, or safety of VISP, our users, or the public.\n• Business transactions: in connection with a merger, acquisition, financing, or sale of assets, subject to appropriate confidentiality safeguards.\n• With your consent: for any other purpose disclosed at the time of collection.\n\nWe do not sell your personal information.' },
    { heading: '6. Data Storage and International Transfers', body: 'VISP currently serves Canadian users. Some of our service providers (including Stripe and cloud hosting partners) may store or process information outside of Canada, including in the United States. When information is transferred outside of Canada, it may be subject to the laws of the jurisdiction where it is stored, including lawful access by foreign authorities. We use contractual and technical safeguards to protect information in transit and at rest.' },
    { heading: '7. Data Retention and Deletion', body: '• Active accounts: we retain your information for as long as your account is active and as needed to provide the Platform.\n• Account deletion: when you delete your account, we retain your information for up to 30 days to allow for recovery, fraud prevention, and dispute completion. After 30 days, personal information is deleted or de-identified, except where longer retention is required by law.\n• Verification documents: ID and background-check documents are retained while you remain a Service Provider and for a reasonable period afterward to comply with legal, audit, and trust-and-safety obligations.\n• Reviews and transaction history: may be retained in anonymized or aggregated form to preserve the integrity of the marketplace.' },
    { heading: '8. Security', body: 'We use industry-standard administrative, technical, and physical safeguards to protect personal information, including encryption in transit, restricted access on a need-to-know basis, and monitoring for unauthorized activity. No system is perfectly secure, and we cannot guarantee absolute security. You are responsible for keeping your account credentials confidential.' },
    { heading: '9. Your Privacy Rights', body: 'Subject to applicable Canadian privacy law, you have the right to:\n\n• Access the personal information we hold about you.\n• Request correction of inaccurate or incomplete information.\n• Withdraw consent for certain processing (subject to legal or contractual restrictions).\n• Request deletion of your account and associated personal information.\n• File a complaint with the Office of the Privacy Commissioner of Canada or your provincial privacy regulator.\n\nTo exercise these rights, contact us using the details in Section 13. We may need to verify your identity before responding.' },
    { heading: "10. Children's Privacy", body: 'The Platform is not intended for individuals under the age of 18. We do not knowingly collect personal information from minors. If we become aware that we have collected personal information from a person under 18, we will delete it promptly.' },
    { heading: '11. Cookies and Similar Technologies', body: 'VISP and our analytics partners use cookies, mobile SDKs, and similar technologies to operate the Platform, remember your preferences, measure performance, and detect fraud. You can control certain technologies through your device or browser settings, although some Platform features may not function correctly if disabled.' },
    { heading: '12. Changes to This Policy', body: 'We may update this Privacy Policy from time to time. Material changes will be communicated through the Platform or by email before they take effect. The "Effective Date" at the top of this Policy indicates when it was last revised.' },
    { heading: '13. Contact Our Privacy Office', body: 'If you have questions, concerns, or requests regarding this Privacy Policy, please contact our Privacy Officer at privacy@vispapp.com. You also have the right to contact the Office of the Privacy Commissioner of Canada at www.priv.gc.ca.' },
  ],
};
